---

- name: Provision | Bootstrapping machines
  hosts: all
  sudo: yes
  roles:
    - base/archlinux
    - base/common

- name: Provision | Installing web ware and app
  hosts: webservers
  sudo: yes
  roles:
    - web/apache-archlinux
    - web/php-archlinux

# - name: Provision | Application
#   hosts: webservers
#   sudo: yes
#   roles:
#     - app
#     - deploy/clean
#     - deploy/update
